### ISSUE TITLE
Add NuGet Package

### ISSUE THREAD

**Issue by Nicholas-Westby** [marcemarc/EditorNotes#2]
Would be useful if there were a NuGet package for this. Makes it easier to manage dependencies without needing to commit binaries to my repos.

**Comment by marcemarc** [comment]
Will do -  it's on the xmas list...
On 22 Dec 2015 19:54, Nicholas-Westby <notifications@github.com> wrote:Would be useful if there were a NuGet package for this Makes it easier to manage dependencies without needing to commit binaries to my repos

**Comment by marcemarc** [comment]
Hey Nicholas, if you could give Install-Package tooorangey.uEditorNotes a whirl and see if this resolves your binary committing issue!

**Comment by Nicholas-Westby** [comment]
Looks good. Thanks!
