### ISSUE TITLE
How about "collapsability" for some notes?

### ISSUE THREAD

**Issue by greystate** [marcemarc/EditorNotes#4]
I've been thinking about a feature for some of the notes in a project we're currently using them in: Some notes can become quite _screen-consuming_ with all the stuff they need to explain, and then when the editor has seen the note a couple of times, it becomes a little redundant and should ideally just be tucked away in a "unpack this crate if you forgot how to do stuff"-crate/box somewhere.

Ever needed that, @marcemarc ? I know you've been using "editor notes" functionality for some time...

I'm thinking we'd need a setting to allow a note to be collapsed/dismissed and some kind of way to persist its current state of _collapsion_, if that makes sense...

Will probably have a go at trying something along those lines.

**Comment by marcemarc** [comment]
Yes, or rather no, I mean over-time I've simplified the notes, and moved them from the top of the tab to the bottom etc, to sort of manage editors 'getting it' and then eventually even removed notes; but haven't thought to enable users to say 'hey I got this - give me some screen space', I like the idea of making the notes always collapsable, and having a prevalue property to determine their opening state,,, the next step would be to allow the note to be dismissed by the editor; but would have to be careful if you updated the note text at a later date, you may want the confident dismissive editor to see the updated text. So with that in mind it's just thinking through where to store the fact they have seen and dismissed it, and at what point in time did that occur; local storage ?

**Comment by greystate** [comment]
Thinking about storing the state, I initially just thought about using a cookie, but LocalStorage seems like a better fit. Wouldn't want to start showing notes that've been dismissed, just because the cookie was deleted (whether manually or otherwise).

A boolean key compiled of **ContentTypeAlias** and **PropertyEditorAlias** would be sufficient, no?
E.g.:

```javascript
// Set
window.localStorage.setItem('Textpage-Content-Note', true);
...
// Get
var noteState = window.localStorage.getItem('Textpage-Content-Note');
if (noteState === true) {
  // Add the '.is-dismissed' CSS class
} 
```

**Comment by marcemarc** [comment]
Yes, I was thinking server side possibly creating a 'RelationType' between parent 'Data Type' and child 'User', so you could 'see' who has seen and dismissed a note - eg has that note been seen by everyone ? etc - but there only appears to be an option for 'member' in a relation type

**Comment by greystate** [comment]
Ah - that could actually be very useful...

**Comment by marcemarc** [comment]
@greystate I have a collapsability branch: https://github.com/marcemarc/EditorNotes/tree/Collapsability/tooorangey.EditorNotes
where I've had a stab at collapsability ... if you have a chance to test and feedback
(collapsability isn't a word is it)

**Comment by greystate** [comment]
I'll definitely give it a spin - thanks!

> (collapsability isn't a word is it[?])

I'll use it as a word until Webster's assimilates it :laughing:

**Comment by marcemarc** [comment]
Main thing I'm puzzling over is what to provide as the default styling, or whether to provide a colour picker of some sort, it's using the bootstrap default markup for a panel; eg if you have 'alert alert-info' etc in the 'Notes Css Class' config, then you get some degree of colour, but it's a toss up between keeping it completely flexible and 'not having to think', 'html' mode should run 'as before', 'collapsible' mode is one of the new options - haven't done relations thing (solving a problem that might not be there)

**Comment by greystate** [comment]
Put it on a site I'm working on - works really nice! :+1: 

Couple of quick thoughts:

- I don't see myself using the 'fly-out' mode much - although if something needs a really long explanation, it might be nice... dunno(?).
- I guess it wouldn't hurt with a `cursor: pointer` on the toggle items (title and arrow)

It's tricky with the CSS stuff - using it on a couple of nodes, fllipping 'round between them, I get the urge to apply the CSS class (e.g. `alert alert-info`) only to the expanded version, so when it's collapsed it's really just a "labeled button" of sorts.

Actually, what I would really want, was for the widget to "just" apply some specific classes (e.g. `note-{alias}` with an added `note-showing` when expanded) and then allow me to point to my own CSS file... but that's *really* pushing it, I know :-)

As it is now, it's already an awesome enhancement :gem:

**Comment by marcemarc** [comment]
@greystate ok I've updated again, to this time include a stylesheet, EditorNotes.css, I'm thinking that this is where you customize your editor notes styles for your back office implementation, generally I would expect the notes to be consistently styled across the back office, ie each presented the same - but you could use the editor specific class, when creating the Data Type if you wanted to target a particular set of styles to a particular editor note - to render it differently to other notes on the site.... and if you don't want to mess around with stylesheets, you can still just add alert alert-info etc to have the bootstrap panel styles from within Umbraco applied... I did the fly-out dialog just because when creating the collapsing notes, I worried that it wasn't very consistent with Umbraco UI and the dialog would probably be the way to do it; that said I prefer the big fat note in the middle of the properties, it seems in context there, and why it's so useful... (if you have time to spin up another test - then I'll package it and nuget it, into the world...)

**Comment by greystate** [comment]
Cool cool cool :-)

Sounds perfect - should be able to test later theis evening. Already looking forward!

**Comment by greystate** [comment]
Hi @marcemarc 

Just gave it another spin and it seems do work great; great with the CSS! I can even style only the panel and keep the toggle nice and clean, e.g.:

```css
.editornote-warning .panel-body {
  color: #314159;
  content: "π";
}
```

(Where `editornote-warning` is the CSS class I specified in the Property Editor Config.)
